'use server';
/**
 * @fileOverview This file implements a Genkit flow to extract editable text from a PDF page image using OCR.
 *
 * - extractEditableTextFromPdf - A function that handles the OCR process for a single PDF page image.
 * - ExtractEditableTextFromPdfInput - The input type for the extractEditableTextFromPdf function.
 * - ExtractEditableTextFromPdfOutput - The return type for the extractEditableTextFromPdf function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import {googleAI} from '@genkit-ai/google-genai';

const ExtractEditableTextFromPdfInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a PDF page, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ExtractEditableTextFromPdfInput = z.infer<typeof ExtractEditableTextFromPdfInputSchema>;

const ExtractEditableTextFromPdfOutputSchema = z.object({
  extractedText: z.string().describe('The extracted editable text from the PDF page image.'),
});
export type ExtractEditableTextFromPdfOutput = z.infer<typeof ExtractEditableTextFromPdfOutputSchema>;

export async function extractEditableTextFromPdf(input: ExtractEditableTextFromPdfInput): Promise<ExtractEditableTextFromPdfOutput> {
  return extractEditableTextFromPdfFlow(input);
}

const extractEditableTextFromPdfPrompt = ai.definePrompt({
  name: 'extractEditableTextFromPdfPrompt',
  input: {schema: ExtractEditableTextFromPdfInputSchema},
  output: {schema: ExtractEditableTextFromPdfOutputSchema},
  model: googleAI.model('gemini-2.5-flash-image'),
  prompt: [
    {
      media: {
        url: '{{{photoDataUri}}}',
      },
    },
    {
      text: 'Extract all text from this image, including any handwritten or printed text. Provide the extracted text as plain, editable text. Format the output as a JSON object with a single field named "extractedText" containing the extracted text.',
    },
  ],
  config: {
    responseModalities: ['TEXT'],
  },
});

const extractEditableTextFromPdfFlow = ai.defineFlow(
  {
    name: 'extractEditableTextFromPdfFlow',
    inputSchema: ExtractEditableTextFromPdfInputSchema,
    outputSchema: ExtractEditableTextFromPdfOutputSchema,
  },
  async (input) => {
    const { output } = await extractEditableTextFromPdfPrompt(input);
    if (!output) {
      throw new Error('No output was generated by the prompt.');
    }
    return output;
  }
);
