"use client";

import React, { useState } from 'react';
import { 
  ArrowLeft, 
  Bot, 
  MessageSquare, 
  Scissors, 
  Copy, 
  Type, 
  FileSearch, 
  ShieldCheck,
  Send,
  Loader2,
  Sparkles,
  RefreshCw,
  MoreHorizontal,
  Download,
  ShieldAlert,
  FileWarning,
  ChevronDown,
  FileType,
  FileImage,
  Image as ImageIcon
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScannedDocument, useAppStore } from '@/lib/store';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Textarea } from '@/components/ui/textarea';
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger 
} from '@/components/ui/dropdown-menu';
import Image from 'next/image';
import { summarizePdfContent } from '@/ai/flows/summarize-pdf-content-flow';
import { chatWithPdfDocument } from '@/ai/flows/chat-with-pdf-document';
import { extractEditableTextFromPdf } from '@/ai/flows/extract-editable-text-from-pdf';
import { suggestSmartFileName } from '@/ai/flows/suggest-smart-file-name-flow';
import { securityAudit } from '@/ai/flows/security-audit-flow';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

interface DocumentEditorProps {
  doc: ScannedDocument;
  onBack: () => void;
}

export const DocumentEditor = ({ doc, onBack }: DocumentEditorProps) => {
  const { updateDocument, setActiveTool } = useAppStore();
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState('view');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [isOCRing, setIsOCRing] = useState(false);
  const [isNaming, setIsNaming] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [chatMessage, setChatMessage] = useState('');
  const [chatHistory, setChatHistory] = useState<{role: 'user' | 'ai', content: string}[]>([]);
  const [isChatting, setIsChatting] = useState(false);

  const handleSummarize = async () => {
    setIsSummarizing(true);
    try {
      const result = await summarizePdfContent({ pdfDataUri: doc.thumbnail });
      updateDocument(doc.id, { summary: result.summary });
      toast({ title: "Analysis Complete", description: "Document summary generated by AI." });
    } catch (err) {
      toast({ title: "AI Error", description: "Failed to summarize document.", variant: "destructive" });
    } finally {
      setIsSummarizing(false);
    }
  };

  const handleOCR = async () => {
    setIsOCRing(true);
    try {
      const result = await extractEditableTextFromPdf({ photoDataUri: doc.thumbnail });
      updateDocument(doc.id, { extractedText: result.extractedText });
      toast({ title: "OCR Successful", description: "Text extracted from image." });
    } catch (err) {
      toast({ title: "OCR Error", description: "Handwriting recognition failed.", variant: "destructive" });
    } finally {
      setIsOCRing(false);
    }
  };

  const handleSecurityAudit = async () => {
    setIsAnalyzing(true);
    try {
      const textToAudit = doc.extractedText || doc.content || "Encrypted byte stream";
      const result = await securityAudit({ 
        documentText: textToAudit,
        fileName: doc.name 
      });
      
      updateDocument(doc.id, { 
        securityStatus: {
          isSafe: result.isSafe,
          threats: result.threats.map(t => t.description),
          pii: result.piiDetected.map(p => `${p.type}: ${p.value}`)
        }
      });
      
      toast({ 
        title: result.isSafe ? "Security Verified" : "Threats Detected", 
        description: result.summary,
        variant: result.isSafe ? "default" : "destructive"
      });
    } catch (err) {
      toast({ title: "Audit Failed", description: "Neural engine timeout.", variant: "destructive" });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleSmartRename = async () => {
    setIsNaming(true);
    try {
      const result = await suggestSmartFileName({ 
        documentText: doc.extractedText || doc.content,
        context: "CyberAegXs Scanned Asset" 
      });
      updateDocument(doc.id, { name: result.suggestedFileName });
      toast({ title: "Identity Re-labeled", description: `New handle: ${result.suggestedFileName}` });
    } catch (err) {
      toast({ title: "Naming Error", description: "AI could not suggest a name.", variant: "destructive" });
    } finally {
      setIsNaming(false);
    }
  };

  const handleExport = (format: 'pdf' | 'jpg' | 'png') => {
    const link = document.createElement('a');
    let extension = format;
    let mimeType = `image/${format === 'jpg' ? 'jpeg' : format}`;
    
    if (format === 'pdf') {
      link.href = doc.thumbnail;
      extension = 'pdf';
    } else {
      const img = new (window as any).Image();
      img.src = doc.thumbnail;
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d');
        if (ctx) {
          ctx.drawImage(img, 0, 0);
          const dataUrl = canvas.toDataURL(mimeType, 0.9);
          link.href = dataUrl;
          link.download = `CyberAegXs_${doc.name.split('.')[0]}.${extension}`;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
        }
      };
      toast({ title: "Synthesis Started", description: `Converting asset to ${format.toUpperCase()}...` });
      return;
    }

    link.download = `CyberAegXs_${doc.name.split('.')[0]}.${extension}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast({ title: "Export Initiated", description: `Encrypted ${format.toUpperCase()} transferred.` });
  };

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatMessage.trim()) return;

    const userMsg = chatMessage;
    setChatHistory(prev => [...prev, { role: 'user', content: userMsg }]);
    setChatMessage('');
    setIsChatting(true);

    try {
      const result = await chatWithPdfDocument({ 
        pdfContent: doc.extractedText || doc.content,
        question: userMsg 
      });
      setChatHistory(prev => [...prev, { role: 'ai', content: result.answer }]);
    } catch (err) {
      setChatHistory(prev => [...prev, { role: 'ai', content: "Node unreachable. Check uplink." }]);
    } finally {
      setIsChatting(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "Copied", description: "Neural data saved to clipboard buffer." });
  };

  return (
    <div className="flex flex-col h-full bg-background animate-in slide-in-from-right duration-300">
      <header className="px-4 lg:px-6 py-4 border-b border-border flex items-center justify-between bg-card shrink-0">
        <div className="flex items-center gap-2 lg:gap-4 overflow-hidden">
          <Button variant="ghost" size="icon" onClick={onBack} className="hover:bg-zinc-800 shrink-0">
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div className="overflow-hidden">
            <div className="flex items-center gap-2">
              <h2 className="font-bold text-sm lg:text-lg truncate max-w-[140px] md:max-w-md">{doc.name}</h2>
              <Button 
                variant="ghost" 
                size="icon" 
                className="h-6 w-6 text-accent hover:text-accent hover:bg-accent/10 shrink-0"
                onClick={handleSmartRename}
                disabled={isNaming}
              >
                {isNaming ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
              </Button>
            </div>
            <div className="flex items-center gap-2 mt-0.5">
              <Badge variant="outline" className="text-[8px] lg:text-[10px] bg-accent/10 border-accent/20 text-accent font-black px-1.5 py-0 uppercase">Vault Secure</Badge>
              <span className="text-[8px] lg:text-[10px] text-zinc-500 font-bold uppercase tracking-widest truncate">{doc.size} • {doc.type.toUpperCase()}</span>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button 
            variant="outline" 
            className="hidden md:flex gap-2 border-zinc-800 hover:bg-zinc-800"
            onClick={handleSecurityAudit}
            disabled={isAnalyzing}
          >
            {isAnalyzing ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4 text-accent" />}
            Scan Security
          </Button>
          
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="bg-primary text-primary-foreground font-black uppercase tracking-widest text-[9px] lg:text-[10px] px-3 lg:px-6 h-8 lg:h-9 gap-2">
                Export <ChevronDown className="h-3 w-3" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-zinc-900 border-zinc-800 text-zinc-300">
              <DropdownMenuItem onClick={() => handleExport('pdf')} className="gap-2 focus:bg-primary focus:text-primary-foreground cursor-pointer">
                <FileType className="h-4 w-4" /> Download as PDF
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport('jpg')} className="gap-2 focus:bg-amber-500 focus:text-white cursor-pointer">
                <ImageIcon className="h-4 w-4" /> Download as JPG
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport('png')} className="gap-2 focus:bg-emerald-500 focus:text-white cursor-pointer">
                <FileImage className="h-4 w-4" /> Download as PNG
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <Button variant="ghost" size="icon" className="hover:bg-zinc-800 h-8 w-8 shrink-0"><MoreHorizontal className="h-5 w-5" /></Button>
        </div>
      </header>

      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
        {/* Left: Viewport */}
        <div className="flex-1 bg-zinc-950 p-4 lg:p-6 flex flex-col items-center overflow-y-auto custom-scrollbar shrink-0 min-h-[40vh] lg:h-full">
          <div className="max-w-2xl w-full bg-zinc-900 shadow-[0_0_50px_rgba(0,0,0,0.5)] rounded-sm overflow-hidden relative border border-white/5 group">
            <Image 
              src={doc.thumbnail} 
              alt="Scan Preview" 
              width={800} 
              height={1000} 
              className="w-full h-auto opacity-90 group-hover:opacity-100 transition-opacity duration-500"
              unoptimized
            />
            <div className="absolute top-4 left-4 bg-black/60 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10 flex items-center gap-2 text-[8px] lg:text-[10px] font-black tracking-widest text-white uppercase">
              <div className="h-1.5 w-1.5 rounded-full bg-accent animate-pulse" />
              Neural View
            </div>
            
            {doc.securityStatus && !doc.securityStatus.isSafe && (
              <div className="absolute bottom-4 left-4 right-4 bg-red-500/90 backdrop-blur-lg p-3 rounded-lg border border-red-400/50 flex items-center justify-between animate-in slide-in-from-bottom-4">
                <div className="flex items-center gap-3">
                  <ShieldAlert className="h-4 w-4 lg:h-5 lg:w-5 text-white" />
                  <span className="text-[8px] lg:text-[10px] font-black text-white uppercase tracking-tighter truncate">Threat: {doc.securityStatus.threats[0]}</span>
                </div>
                <Button size="sm" variant="ghost" className="h-7 text-white hover:bg-white/10 text-[8px] lg:text-[10px] font-black uppercase shrink-0">Isolate</Button>
              </div>
            )}
          </div>
        </div>

        {/* Right: Sidebar Tools */}
        <div className="w-full lg:w-96 bg-card border-t lg:border-t-0 lg:border-l border-border flex flex-col h-[50vh] lg:h-full shadow-2xl shrink-0">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden">
            <div className="px-4 pt-4 shrink-0">
              <TabsList className="w-full bg-zinc-900 border border-zinc-800 p-1 rounded-xl">
                <TabsTrigger value="view" className="flex-1 gap-2 text-[9px] lg:text-[10px] font-black uppercase tracking-widest rounded-lg data-[state=active]:bg-zinc-800"><Bot className="h-3.5 w-3.5" /> AI Tools</TabsTrigger>
                <TabsTrigger value="chat" className="flex-1 gap-2 text-[9px] lg:text-[10px] font-black uppercase tracking-widest rounded-lg data-[state=active]:bg-zinc-800"><MessageSquare className="h-3.5 w-3.5" /> Chat</TabsTrigger>
                <TabsTrigger value="edit" className="flex-1 gap-2 text-[9px] lg:text-[10px] font-black uppercase tracking-widest rounded-lg data-[state=active]:bg-zinc-800"><Scissors className="h-3.5 w-3.5" /> Edit</TabsTrigger>
              </TabsList>
            </div>

            <TabsContent value="view" className="flex-1 overflow-y-auto p-4 space-y-6 custom-scrollbar">
              <div className="space-y-3">
                <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-500 ml-1">Document Insights</h4>
                {doc.summary ? (
                  <div className="p-4 rounded-2xl bg-primary/5 border border-primary/20 animate-in fade-in slide-in-from-top-2 relative group">
                    <div className="flex items-center gap-2 text-primary font-black text-[10px] mb-2 uppercase tracking-widest">
                      <Sparkles className="h-3.5 w-3.5" /> AI Neural Summary
                    </div>
                    <p className="text-xs leading-relaxed text-zinc-300 font-medium">{doc.summary}</p>
                    <button 
                      onClick={handleSummarize}
                      className="absolute top-4 right-4 text-zinc-600 hover:text-primary transition-colors"
                    >
                      <RefreshCw className={cn("h-3 w-3", isSummarizing && "animate-spin")} />
                    </button>
                  </div>
                ) : (
                  <Button 
                    className="w-full h-12 lg:h-14 bg-zinc-950 hover:bg-zinc-900 border border-zinc-800 text-zinc-400 font-black uppercase tracking-widest text-[9px] lg:text-[10px] gap-3 rounded-2xl transition-all"
                    onClick={handleSummarize}
                    disabled={isSummarizing}
                  >
                    {isSummarizing ? <Loader2 className="h-4 w-4 animate-spin text-primary" /> : <Bot className="h-4 w-4 text-primary" />}
                    Summarize Document
                  </Button>
                )}
              </div>

              <div className="space-y-3">
                <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-500 ml-1">Text Recognition</h4>
                {doc.extractedText ? (
                  <div className="space-y-3">
                    <div className="relative group">
                      <Textarea 
                        value={doc.extractedText} 
                        className="min-h-[120px] lg:min-h-[180px] bg-zinc-950 border-zinc-800 text-xs font-medium text-zinc-400 rounded-2xl resize-none focus:ring-accent/20"
                        readOnly
                      />
                    </div>
                    <Button 
                      variant="outline" 
                      className="w-full h-10 lg:h-12 gap-2 border-zinc-800 hover:bg-white hover:text-zinc-950 font-black uppercase text-[9px] lg:text-[10px] tracking-widest rounded-xl transition-all"
                      onClick={() => copyToClipboard(doc.extractedText!)}
                    >
                      <Copy className="h-3.5 w-3.5" /> Copy Data
                    </Button>
                  </div>
                ) : (
                  <Button 
                    className="w-full h-12 lg:h-14 bg-zinc-950 hover:bg-zinc-900 border border-zinc-800 text-zinc-400 font-black uppercase tracking-widest text-[9px] lg:text-[10px] gap-3 rounded-2xl transition-all"
                    onClick={handleOCR}
                    disabled={isOCRing}
                  >
                    {isOCRing ? <Loader2 className="h-4 w-4 animate-spin text-accent" /> : <Type className="h-4 w-4 text-accent" />}
                    Extract Editable Text
                  </Button>
                )}
              </div>

              <div className="grid grid-cols-2 gap-3 pb-4">
                <Button 
                  variant="outline" 
                  className={cn(
                    "border-zinc-800 flex flex-col h-auto py-4 lg:py-5 gap-2 rounded-2xl group transition-all",
                    doc.securityStatus?.pii.length ? "bg-amber-500/10 border-amber-500/30" : "hover:border-accent hover:bg-accent/5"
                  )}
                  onClick={handleSecurityAudit}
                  disabled={isAnalyzing}
                >
                  {isAnalyzing ? <Loader2 className="h-5 w-5 animate-spin text-accent" /> : <FileSearch className="h-5 w-5 text-accent group-hover:scale-110 transition-transform" />}
                  <span className="text-[8px] lg:text-[9px] font-black uppercase tracking-[0.1em]">Detect PII</span>
                </Button>
                <Button 
                  variant="outline" 
                  className={cn(
                    "border-zinc-800 flex flex-col h-auto py-4 lg:py-5 gap-2 rounded-2xl group transition-all",
                    doc.securityStatus?.threats.length ? "bg-red-500/10 border-red-500/30" : "hover:border-emerald-500 hover:bg-emerald-500/5"
                  )}
                  onClick={handleSecurityAudit}
                  disabled={isAnalyzing}
                >
                  {isAnalyzing ? <Loader2 className="h-5 w-5 animate-spin text-emerald-500" /> : <ShieldCheck className="h-5 w-5 text-emerald-500 group-hover:scale-110 transition-transform" />}
                  <span className="text-[8px] lg:text-[9px] font-black uppercase tracking-[0.1em]">Anti-Virus</span>
                </Button>
              </div>
            </TabsContent>

            <TabsContent value="chat" className="flex-1 flex flex-col overflow-hidden">
              <ScrollArea className="flex-1 p-4">
                <div className="space-y-4">
                  <div className="p-3 lg:p-4 bg-zinc-950 rounded-2xl text-[9px] lg:text-[11px] text-zinc-500 border border-zinc-800 font-bold uppercase leading-relaxed tracking-tight">
                    Node: CyberAI Online. Document indexed. Awaiting neural queries.
                  </div>
                  {chatHistory.map((msg, i) => (
                    <div key={i} className={cn(
                      "flex flex-col max-w-[90%] animate-in slide-in-from-bottom-2",
                      msg.role === 'user' ? "ml-auto items-end" : "items-start"
                    )}>
                      <div className={cn(
                        "p-3 rounded-2xl text-xs font-medium",
                        msg.role === 'user' 
                          ? "bg-primary text-primary-foreground rounded-tr-none shadow-lg shadow-primary/10" 
                          : "bg-zinc-800 text-white rounded-tl-none border border-zinc-700"
                      )}>
                        {msg.content}
                      </div>
                    </div>
                  ))}
                  {isChatting && (
                    <div className="flex items-center gap-2 text-zinc-500 text-[10px] font-black uppercase tracking-widest italic animate-pulse px-2">
                      <Loader2 className="h-3 w-3 animate-spin" /> Thinking...
                    </div>
                  )}
                </div>
              </ScrollArea>
              <div className="p-4 border-t border-border bg-card shrink-0">
                <form onSubmit={handleSendMessage} className="flex gap-2">
                  <Input 
                    placeholder="Query Document..." 
                    className="bg-zinc-950 border-zinc-800 h-10 lg:h-12 rounded-xl text-xs font-bold focus:border-accent"
                    value={chatMessage}
                    onChange={(e) => setChatMessage(e.target.value)}
                  />
                  <Button type="submit" size="icon" className="bg-accent text-accent-foreground shrink-0 h-10 lg:h-12 w-10 lg:w-12 rounded-xl shadow-lg shadow-accent/20" disabled={isChatting || !chatMessage.trim()}>
                    <Send className="h-4 w-4" />
                  </Button>
                </form>
              </div>
            </TabsContent>

            <TabsContent value="edit" className="flex-1 p-4 space-y-3 lg:space-y-4 overflow-y-auto custom-scrollbar">
              <Button 
                className="w-full justify-start gap-4 h-12 lg:h-14 border-zinc-800 bg-zinc-950/50 hover:bg-zinc-900 rounded-2xl font-black uppercase text-[9px] lg:text-[10px] tracking-widest" 
                variant="outline"
                onClick={() => setActiveTool('remove')}
              >
                <Scissors className="h-4 w-4 text-red-500" /> Remove Pages
              </Button>
              <Button 
                className="w-full justify-start gap-4 h-12 lg:h-14 border-zinc-800 bg-zinc-950/50 hover:bg-zinc-900 rounded-2xl font-black uppercase text-[9px] lg:text-[10px] tracking-widest" 
                variant="outline"
                onClick={() => {
                  setActiveTool('merge');
                }}
              >
                <FilesIcon className="h-4 w-4 text-primary" /> Merge PDF
              </Button>
              <Button 
                className="w-full justify-start gap-4 h-12 lg:h-14 border-zinc-800 bg-zinc-950/50 hover:bg-zinc-900 rounded-2xl font-black uppercase text-[9px] lg:text-[10px] tracking-widest" 
                variant="outline"
                onClick={() => setActiveTool('compress')}
              >
                <Download className="h-4 w-4 text-emerald-500" /> Optimize Size
              </Button>
              
              <div className="pt-4 border-t border-border">
                <h4 className="text-[10px] font-black uppercase tracking-[0.3em] text-zinc-500 mb-3 ml-1">Synthesis Conversion</h4>
                <div className="grid grid-cols-2 gap-3 pb-4">
                  <Button 
                    variant="outline" 
                    className="text-[9px] lg:text-[10px] font-black uppercase tracking-widest h-12 lg:h-14 border-zinc-800 bg-zinc-950/50 hover:bg-blue-500 hover:text-white rounded-2xl"
                    onClick={() => setActiveTool('pdf-to-word')}
                  >
                    To Word
                  </Button>
                  <Button 
                    variant="outline" 
                    className="text-[9px] lg:text-[10px] font-black uppercase tracking-widest h-12 lg:h-14 border-zinc-800 bg-zinc-950/50 hover:bg-amber-500 hover:text-white rounded-2xl"
                    onClick={() => setActiveTool('pdf-to-jpg')}
                  >
                    To Image
                  </Button>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  );
};

function FilesIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.5 2H8.6c-.4 0-.8.2-1.1.5-.3.3-.5.7-.5 1.1v12.8c0 .4.2.8.5 1.1.3.3.7.5 1.1.5h9.8c.4 0 .8-.2 1.1-.5.3-.3.5-.7.5-1.1V6.5L15.5 2z" />
      <path d="M3 7.6v12.8c0 .4.2.8.5 1.1.3.3.7.5 1.1.5h9.8" />
      <path d="M15 2v4.5h4.5" />
    </svg>
  );
}